### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by chrislopresto** [chrislopresto/ember-freestyle#10]
Create a README with basic usage instructions to hold folks over until we have a proper documentation site.

Relevant PRs:
- https://github.com/chrislopresto/ember-freestyle/pull/41

**Comment by flexyford** [comment]
Excited for this README. Congrats on the great Ember-Conf talk this year :smile:

**Comment by knownasilya** [comment]
Yeah, trying to use this an an app, but totally not sure where to define the styleguide items, since there is no dummy app in a normal app.

**Comment by knownasilya** [comment]
For anyone wanting to jump in, see the dummy app in this repo, i.e. https://github.com/chrislopresto/ember-freestyle/blob/master/tests/dummy/app/templates/application.hbs

**Comment by chrislopresto** [comment]
@knownasilya Thanks for writing this up. The dummy app is definitely the best way to copy/paste/get going. I'll start writing up better instructions today.

As for the json files, that is a separate spike to hydrate both JS and SCSS from a common JSON config file. I really like the idea, and it backs the current implementation of the `freestyle-color-palette` component. But I think I'll end up extracting all of this to a separate addon so people don't get confused. If it's interfering with any initial setup, I'll create an issue and fix it up.

**Comment by knownasilya** [comment]
> But I think I'll end up extracting all of this to a separate addon so people don't get confused. If it's interfering with any initial setup, I'll create an issue and fix it up.

Yes please! The biggest hassle has been that and the SASS.

**Comment by chrislopresto** [comment]
Yes. The sass extract is top priority. https://github.com/chrislopresto/ember-freestyle/issues/15

**Comment by chrislopresto** [comment]
Making headway on this: https://github.com/chrislopresto/ember-freestyle/pull/41

**Comment by chrislopresto** [comment]
I'm going to declare this issue closed, as we now have a basic README in place. We'll track creation of a proper docs site in a separate issue.
