### ISSUE TITLE
Error: File to import not found or unreadable: ember-freestyle

### ISSUE THREAD

**Issue by ming-codes** [chrislopresto/ember-freestyle#120]
This is during upgrade from `0.2.14` to `0.4.1`. It looks like `app/styles/ember-freestyle.scss` is gone in this version.

**Comment by chrislopresto** [comment]
Hi @ming-codes. Sorry for the confusion, but this is an expected breaking change when upgrading to 0.4 and beyond. We decided to rework how Ember Freestyle is providing its CSS to consuming apps.

The [v0.4.0 Release Notes](https://github.com/chrislopresto/ember-freestyle/releases/tag/v0.4.0) explain that apps need to remove `@import 'ember-freestyle';` from your app.scss file, but perhaps we should add this to the top of the README. You're not the first person to get tripped up by this.

Would you be interested in providing a quick PR?

Cheers!

Duplicates https://github.com/chrislopresto/ember-freestyle/issues/115
