### ISSUE TITLE
Documentation and Blueprints Do Not Match v0.6.0

### ISSUE THREAD

**Issue by tomoguisuru** [chrislopresto/ember-freestyle#132]
The documentation is no longer valid with the v0.6.0 release an creates confusion for new users of the addon

Also, the default blueprints no longer work and provide no useful examples

**Comment by chrislopresto** [comment]
Thanks for reporting. I just released 0.6.1 which includes a fix for the blueprint.

As for the documentation, I got rid of the separate, outdated docs project. Now [ember-freestyle.com](//ember-freestyle.com) serves up the dummy app from this repository. We still need to improve the documentation, but it is now current.
