### ISSUE TITLE
Latest version seems broken?

### ISSUE THREAD

**Issue by thomblake** [chrislopresto/ember-freestyle#138]
I filed an issue at https://github.com/stefanpenner/async-disk-cache/issues/58 which I think is where the error is, but figured I'd post something here too to see what's up

When trying to build after upgrading freestyle, I see `TypeError: heimdall.hasMonitor is not a function`

**Comment by lukemelia** [comment]
@chrislopresto I think this can be closed given the delay and that lots of people have been successfully using freestyle.

**Comment by chrislopresto** [comment]
Closing this, as freestyle things appear to be working. Cheers.
