### ISSUE TITLE
Error: File not found: addon.sass

### ISSUE THREAD

**Issue by Biszkopt91** [chrislopresto/ember-freestyle#143]
I'm adding `ember-freestyle` to my project using instruction, but during building `broccoli` throws error related to `addon.sass.`. Without this package, the error doesn't occur. I try to import styles in `app.sass` `@import 'ember-freestyle'` or add it to `ember-cli-build` like:
 ```
nodeAssets: {    
  "ember-freestyle": {
      srcDir: "addon/styles",
      import: ["addon.sass"]
   }
 },
```

Error:
![error](https://user-images.githubusercontent.com/17613900/31170290-cd4c79a2-a8fb-11e7-965f-24ca0ae58127.PNG)

Project dependencies:
```
"dependencies": {
    "cirilla": "1.0.5",
    "ember-cli-babel": "6.8.2",
    "ember-cli-htmlbars": "2.0.3",
    "ember-cli-htmlbars-inline-precompile": "1.0.2",
    "ember-cli-sass": "7.0.0",
    "ember-power-select": "1.9.6"
  },
  "devDependencies": {
    "@ac/addon-code-quality": "0.1.1",
    "@ac/eslint-config": "0.2.3",
    "babel-plugin-preval": "1.5.0",
    "broccoli-asset-rev": "2.6.0",
    "cross-env": "5.0.5",
    "ember-ajax": "3.0.0",
    "ember-cli": "2.15.1",
    "ember-cli-babel": "6.8.2",
    "ember-cli-dependency-checker": "1.3.0",
    "ember-cli-eslint": "4.2.0",
    "ember-cli-inject-live-reload": "1.7.0",
    "ember-cli-moment-shim": "^3.5.0",
    "ember-cli-qunit": "4.0.1",
    "ember-cli-sass-lint": "1.0.5",
    "ember-cli-shims": "1.1.0",
    "ember-cli-sri": "2.1.1",
    "ember-cli-template-lint": "0.7.3",
    "ember-cli-uglify": "1.2.0",
    "ember-cp-validations": "3.4.1",
    "ember-disable-prototype-extensions": "1.1.2",
    "ember-export-application-global": "2.0.0",
    "ember-file-upload": "2.1.1",
    "ember-load-initializers": "1.0.0",
    "ember-moment": "7.4.1",
    "ember-native-dom-helpers": "0.5.4",
    "ember-radio-button": "1.1.1",
    "ember-resolver": "4.5.0",
    "ember-source": "2.14.1",
    "ember-truth-helpers": "1.3.0",
    "loader.js": "4.6.0",
    "sass-lint": "1.10.2"
  },
```
`@ac` is a namespace to our internal registry.

**Comment by PoslinskiNet** [comment]
@Biszkopt91 I think it is connected with https://github.com/aexmachina/ember-cli-sass/issues/163 ... ember-freestyle has  `addon.scss`, but the project supports `*.sass` (based on `ember-cli-sass` setting)

**Comment by PoslinskiNet** [comment]
I made a repo that contains the minimal setup that reproduce the issue:

https://github.com/PoslinskiNet/ember-freestyle-fix

**Comment by PoslinskiNet** [comment]
@chrislopresto maybe we could move to `.css` approach to avoid cross-extension node-sass issues? Would you merge such a PR if anyone would prepare one of these?

**Comment by chrislopresto** [comment]
Wow, that's a bummer! Because node-sass can handle scss and sass files side by side, I never thought about extension battles in ember-cli-sass.

Because of this issue and other past issues, I'd like to move to a vanilla CSS approach. @PoslinskiNet would you be willing to open a PR?

**Comment by PoslinskiNet** [comment]
@Biszkopt91 @chrislopresto Pull request is on the place. Feedback is welcome.

**Comment by bertdeblock** [comment]
👋 `ember-cli-sass` and `sass` are ditched in `v0.13.2`, so normally, this shouldn't be an issue anymore.
