### ISSUE TITLE
Supported Ember versions

### ISSUE THREAD

**Issue by ctjhoa** [chrislopresto/ember-freestyle#153]
Hi,

I've tried to run test on `ember 2.4.6` with `ember-freestyle 0.6.2` because I cannot see what's breaking changes could prevent us to use it and the tests seems to pass:
```
Scenario ember-lts-2.4: SUCCESS
Command run: ember test
┌────────────────────┬────────────────────┬──────────────────────────────┬──────────┐
│ Dependency         │ Expected           │ Used                         │ Type     │
├────────────────────┼────────────────────┼──────────────────────────────┼──────────┤
│ ember-source       │ Not Installed      │ Not Installed                │ yarn     │
├────────────────────┼────────────────────┼──────────────────────────────┼──────────┤
│ ember              │ components/ember#… │ 2.4.6                        │ bower    │
└────────────────────┴────────────────────┴──────────────────────────────┴──────────┘
```

(`ember 1.13.13` failed without surprise)

According to the documentation `ember 2.4.6`should be limited to `ember-freestyle 0.3.0`.
As far as I understand your project vision, you only *guarantee* compatibility with the latest 2 ember LTS but your project could work with earlier version of ember.

Could you confirm this? If the answer is "yes" I think that you should differentiate "compatibility versions" and "supported versions" because there is no reasons to freeze `ember-freestyle` if there is no breaking changes.

Thanks

**Comment by chrislopresto** [comment]
@ctjhoa That's correct, and thanks for verifying that everything still works with `2.4.6`. Would you be willing to open a PR, updating the documentation?

Thanks!

**Comment by ctjhoa** [comment]
done
