### ISSUE TITLE
Please upgrade ember-cli-sass to 7.2.0

### ISSUE THREAD

**Issue by tamzinblake** [chrislopresto/ember-freestyle#170]
ember-freestyle currently depends on outdated ember-cli-sass which depends on outdated ember-cli-version-checker which causes this deprecation https://github.com/ember-cli/ember-cli-version-checker/issues/48

Upgrading to 7.2.0 will fix this issue.

**Comment by backspace** [comment]
This appears to have happened in #191!

**Comment by chrislopresto** [comment]
@tamzinblake @backspace Yup! The 0.11.x releases I just cut include the ember-cli-sass upgrade.
