### ISSUE TITLE
Removing ember-cli-sass dependency

### ISSUE THREAD

**Issue by musaffa** [chrislopresto/ember-freestyle#172]
I've migrated from sass to postcss. I still use sass syntax (variables, import) in postcss, but I don't need ember-cli-sass to do it. This is the only addon in my app which has a sass dependency. I would love to see this dependency removed. Those who want to override the sass variables of `ember-freestyle` can install ember-cli-sass on their own. Thanks.

**Comment by PoslinskiNet** [comment]
Seems like related: https://github.com/chrislopresto/ember-freestyle/pull/152

**Comment by bertdeblock** [comment]
Is this still an issue now that `node-sass` isn't used anymore?

**Comment by bertdeblock** [comment]
@patrickberkeley FYI, `ember-cli-sass` and `sass` are ditched in `v0.13.2`.

**Comment by patrickberkeley** [comment]
Thanks @bertdeblock ! We've been following your work here, and have a ticket to upgrade and remove sass.
