### ISSUE TITLE
Error while processing route

### ISSUE THREAD

**Issue by nizarayari** [chrislopresto/ember-freestyle#175]
I can't import ember-data-factory-guy from dummy app controller. I have this error :
**freestyle Could not find module `ember-data-factory-guy` imported from `dummy/controllers/freestyle` Error: Could not find module `ember-data-factory-guy` imported from `dummy/controllers/freestyle**

In my `tests/dummy/app/controllers/freestyle.js`, I have:
```javascript
import FreestyleController from 'ember-freestyle/controllers/freestyle'
import FactoryGuy from 'ember-data-factory-guy'
import loadFactories from 'ember-data-factory-guy/utils/load-factories'

export default FreestyleController.extend({
  emberFreestyle: inject(),

  init() {
    this._super(...arguments)
    loadFactories()

    this.setProperties({
      user: FactoryGuy.make('user'),
      organization: FactoryGuy.make('organization'),
      transfer: FactoryGuy.make('transfer'),
      transfer2: FactoryGuy.make('transfer'),
      transfer3: FactoryGuy.make('transfer'),
   })
 }
})
```

It occurs only when I serve the dummy app in production mode, not in dev mode. Any idea plz?

**Comment by lukemelia** [comment]
By default, ember-data-factory-guy is not enabled in production builds. See https://github.com/danielspaniel/ember-data-factory-guy#using-in-other-environments for info on how to enable it.

**Comment by chrislopresto** [comment]
Thanks, @lukemelia. @nizarayari, the ember-data-factory-guy documentation linked should do the trick, so I'm going to close this issue here.
