### ISSUE TITLE
Warning: Plugin uses .read/.rebuild API

### ISSUE THREAD

**Issue by Turbo87** [chrislopresto/ember-freestyle#186]
After updating to `ember-cli@3.4.2` I've started seeing the following warnings from broccoli, which seem to originate in `ember-freestyle`:

```
[API] Warning: The .read and .rebuild APIs will stop working in the next Broccoli version
[API] Warning: Use broccoli-plugin instead: https://github.com/broccolijs/broccoli-plugin
[API] Warning: Plugin uses .read/.rebuild API: Remover
[API] Warning: Plugin uses .read/.rebuild API: Flatiron
[API] Warning: Plugin uses .read/.rebuild API: SnippetFinder
```

**Comment by Turbo87** [comment]
@lukemelia @chrislopresto it seems like this issue is already resolved on the current `master` branch, but not released yet. are you planning a new release in the near future?

**Comment by jherdman** [comment]
FYI this is causing apps upgrading to 3.5 to crash.

**Comment by Turbo87** [comment]
@lukemelia @chrislopresto friendly reminder 🙏

**Comment by Alonski** [comment]
@Turbo87 I think this can be closed:
https://github.com/chrislopresto/ember-freestyle/blob/362a984613f415aa6f22845292a8c24c15a7ea56/CHANGELOG.md#v0100-2018-11-07

**Comment by Turbo87** [comment]
yeah, thanks!
