### ISSUE TITLE
Make ember freestyle components AngleBracket invocation compatible

### ISSUE THREAD

**Issue by Windvis** [chrislopresto/ember-freestyle#188]
AngleBracket invocation [does not support positional params](https://github.com/emberjs/rfcs/blob/master/text/0311-angle-bracket-invocation.md#positional-arguments).

It looks a bit silly when some components use AngleBrackets and others do not.

**Comment by NindroidX** [comment]
Looks like using `@slug= / slug=` just works. So maybe just changing the docs is enough?

```hbs
<FreestyleUsage @slug="typography-roboto-slab-bold" @title="RobotoSlab-bold">
  <FreestyleTypeface @fontFamily="Roboto Slab" />
</FreestyleUsage>
```

**Comment by Windvis** [comment]
Using AngleBrackets for the FreestyleUsage component breaks the snippet functionality though.

[This file](https://github.com/chrislopresto/ember-freestyle/blob/b57bff3fdfaa2b02f7c751c4f9e5ecc546e3442c/freestyle-usage-snippet-finder.js#L28) would need more work to make it AngleBrackets compatible.

**Comment by rondale-sc** [comment]
@Windvis I'm running into similar problems.  `@slug=` does the trick, but with Octane / Glimmer Components it doesn't find the co-located templates.

Has anyone run into this with Octane?

**Comment by chrislopresto** [comment]
@Windvis @rondale-sc I don’t have time to work on this refactor, but I’d be happy to help if someone else takes the lead.

**Comment by suzidao** [comment]
@chrislopresto took a whack at it because we want to use this add-on for an oncoming ember-octane project. just opened PR #300

**Comment by chrislopresto** [comment]
@suzidao I just left a review on #300. Great work so far! After a few tweaks, we'll be good to merge. Let me know if you have any questions.

Thanks!
