### ISSUE TITLE
"Overriden computed property" deprecation warning

### ISSUE THREAD

**Issue by Turbo87** [chrislopresto/ember-freestyle#194]
> DEPRECATION: The <ogn-web-viewer@component:freestyle-snippet::ember202>#dynamicProperties computed property was just overriden. This removes the computed property and replaces it with a plain value, and has been deprecated. If you want this behavior, consider defining a setter which does it manually. [deprecation id: computed-property.override] See https://emberjs.com/deprecations/v3.x#toc_computed-property-override for more details.

I've started seeing the above deprecation warnings on the freestyle route after upgrading to Ember v3.9

**Comment by chrislopresto** [comment]
@Turbo87 This should be fixed as of 0.11.3.
