### ISSUE TITLE
Releasing the ember-cli-sass change would be awesome

### ISSUE THREAD

**Issue by Vaporbook** [chrislopresto/ember-freestyle#197]
I noticed that https://github.com/chrislopresto/ember-freestyle/commit/b57bff3fdfaa2b02f7c751c4f9e5ecc546e3442c bumps up to ember-cli-sass@10 and uses dart-sass. But it's not released yet. It would be awesome to get a release of that - we are trying to eliminate node-sass from our build chain. It seems like it may address a few other open issues as well. Thanks!

**Comment by elidupuis** [comment]
Yes please 🙏 
I just ran into this while trying to upgrade our app to Node 10.

```
Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.8.3
```

And the only reason `node-sass` is in our app is ember-freestyle:

```
=> Found "node-sass@4.8.3"
info Reasons this module exists
   - "ember-freestyle#ember-cli-sass#broccoli-sass-source-maps" depends on it
   - Hoisted from "ember-freestyle#ember-cli-sass#broccoli-sass-source-maps#node-sass"
```

**Comment by chrislopresto** [comment]
@Vaporbook @elidupuis The 0.11.x releases I just cut have the ember-cli-sass updates. Sorry for the delay!
