### ISSUE TITLE
domain ember-freestyle.com has expired

### ISSUE THREAD

**Issue by rafael-paiva** [chrislopresto/ember-freestyle#213]
When I try to visit http://ember-freestyle.com/ I see the following error:

```
ember-freestyle.com has expired.

If you know the owner of this domain, please let them know.
```

**Comment by amyrlam** [comment]
Came to post the thing. Possible to host on GitHub pages, is free?

**Comment by chrislopresto** [comment]
Thanks, folks. I just set up everything at https://chrislopresto.github.io/ember-freestyle/

**Comment by ro0gr** [comment]
@chrislopresto there is an old link left on the top of the GH repository main page

**Comment by chrislopresto** [comment]
@ro0gr I fixed the link at the repository page. Let me know if I missed anything else.
