### ISSUE TITLE
Inline snippets not rendering

### ISSUE THREAD

**Issue by wireframe** [chrislopresto/ember-freestyle#30]
I've run the example "dummy" app multiple times and things work great, but when I use the addon generators w/ nearly the exact same markup, I don't see any of the inline rendered snippets for code/markup/etc.

I have this issue with my custom components as well as the default freestyle-palette components.

Any tips for how to debug/troubleshoot?

**Comment by chrislopresto** [comment]
@wireframe I'm happy to help out and see what's going on, but I'll need some details. Can you copy/paste code samples or share links to a public gist or repository?

**Comment by wireframe** [comment]
I'll do my best to create a simple testcase.  My guess at the moment is that it may have something to do with organizing my components into pods?

I'm using the [ember-component-css](https://github.com/ebryn/ember-component-css) addon which requires pods at the moment.

**Comment by chrislopresto** [comment]
You may need to specify `snippetSearchPaths` like this: https://github.com/chrislopresto/ember-freestyle/blob/789cbb272eccf742c07d322c2783d37a547a03f6/ember-cli-build.js#L12

By default, ember-freestyle looks in `app`. I obviously need to document this!

**Comment by chrislopresto** [comment]
FYI, the technique comes from https://github.com/ef4/ember-code-snippet

**Comment by chrislopresto** [comment]
@wireframe Let me know if this resolves things for you.

**Comment by wireframe** [comment]
Thanks Chris.  I'll try to test out this change today!

---
Ryan Sonnek
ryan.sonnek@gmail.com

**Comment by wireframe** [comment]
Unfortunately, No :dice: using this approach.  It could easily be user error, but I've been unable to trace down the root cause of this issue.

I'm going to have to table this issue for the time being, and you can feel free to close out this issue until I have time to revisit it further.

**Comment by mszoernyi** [comment]
@wireframe Is you `freestyle.hbs` shareable? I'm using a pod structure as well with `ember-component-css` and I'm just about to setup everything. I could try your setting on the way and figure out what setting you need to set.

**Comment by mszoernyi** [comment]
I would suggest we add some sane defaults for the snippet path based on the `usePods` flag.

`snippetSearchPaths` for pod structure: `['tests/dummy/app', 'app']`
`snippetSearchPaths` for normal structure: `['tests/dummy/app/styles', 'app/styles']`

**Comment by niltz** [comment]
I think I am having a similar issue. I found that inline snippets in my scss files are not found, but if I put them in a js file (like the freestyle.js controller) then they are found.

The scss files are in the app folder, so I believe they should be in the snippetSearchPaths by default.

The example snippet that works in js but not scss is:
```
/* BEGIN-FREESTYLE-USAGE modules-buttons-normal:notes

Use these whenever you need some kind of clickable surface to afford an action that
isn't a boring, inconspicuous text link.

END-FREESTYLE-USAGE */
```

**Comment by chrislopresto** [comment]
@niltz I just realized that I never wired up SCSS notes snippets. https://github.com/chrislopresto/ember-freestyle/pull/63 will do the trick. I'll merge it and cut a new release.

**Comment by chrislopresto** [comment]
FYI, this whole setup needs to be cleaned up. I think these are the two next issues  to focus on:

- [Simplify Technique for Including Notes #61](https://github.com/chrislopresto/ember-freestyle/issues/61)
- [Support different FREESTYLE-USAGE-* code snippet delimiters #48](https://github.com/chrislopresto/ember-freestyle/issues/48)

**Comment by chrislopresto** [comment]
@niltz I just published v0.2.12, which supports SCSS note snippets. You can see it in action here:

**Source**
https://github.com/chrislopresto/ember-freestyle/blob/3debca529aae0235c579e7767179453558685e9d/app/styles/components/freestyle-palette-item.scss#L1-L9

```scss
/* BEGIN-FREESTYLE-USAGE fpi:notes
# Markdown Notes In SCSS!

Hey look... these are `markdown` notes:

- coming from scss
- looking nice

END-FREESTYLE-USAGE */
```

**Rendered**
http://chrislopresto.github.io/ember-freestyle/?f=fpi&m=false&s=Visual%20Style&ss=Color

**Comment by niltz** [comment]
@chrislopresto v0.2.12 fixes my issue. Thanks!

**Comment by chrislopresto** [comment]
@wireframe I'm going to close this for now. Feel free to reopen or open a new issue if your problem persists.
