### ISSUE TITLE
Provide mechanism to remove from production build

### ISSUE THREAD

**Issue by chrislopresto** [chrislopresto/ember-freestyle#31]
Document how to use https://github.com/kellyselden/ember-cli-funnel to exclude Freestyle-related content from production builds.

Rather than carry this as an explicit dependency, let's just document how to go about it. This will avoid conflicting with other unrelated use of ember-cli-funnel. It will also allow people to put some Freestyle guides/components in production while excluding others... will avoid the need to track/infer what portions of the app are using freestyle components... etc.

**Comment by GCheung55** [comment]
Nice. I was just thinking about this. My team might not want the style guide out in prod.

**Comment by kellyselden** [comment]
This *might* be easy using https://github.com/kellyselden/ember-cli-funnel

**Comment by chrislopresto** [comment]
Nice!

**Comment by josemarluedke** [comment]
Would love to get this done automatically. In the mean time, can a documentation be provided to accomplish this?

**Comment by jamesarosen** [comment]
My use-case for this (or something like it) is to add freestyle documentation to an *addon*. That is, in development mode my library becomes a documentation-only app. When included in another app, my addon's documentation should be excluded.

**Comment by oligriffiths** [comment]
@chrislopresto Yeah, we need a way of removing freestyle from production, this should be dev only by default. Any update on this?

**Comment by simonihmig** [comment]
Here is my attempt: #98
