### ISSUE TITLE
Wrong info in "Compatibility" section?

### ISSUE THREAD

**Issue by bertdeblock** [chrislopresto/ember-freestyle#337]
Due to the Ember CLI update, the "Compatibility" section was overwritten. I'm not sure if the current info is correct.

**Comment by lukemelia** [comment]
@bertdeblock we're now testing with Ember/Ember CLI 3.8 and up. Sorry for the confusion. Master should have the correct info now.

**Comment by bertdeblock** [comment]
@lukemelia The support section says: `Ember Freestyle support is only provided for the 2 latest Ember versions`. So shouldn't we be testing against 3.12 and 3.16? Assuming `2 latest Ember versions` means 2 latest LTS versions.
