### ISSUE TITLE
Support different FREESTYLE-USAGE-* code snippet delimiters

### ISSUE THREAD

**Issue by chrislopresto** [chrislopresto/ember-freestyle#48]
### Problem

Currently, code snippets are delimited using comments of the form `// BEGIN-FREESTYLE-USAGE unique-slug`.

There is also a hacky technique of appending `:notes` to the end of the slug to indicate that the snippet content is in fact markdown: `/* BEGIN-FREESTYLE-USAGE unique-slug:notes`. This allows the `freestyle-usage` component to render both "regular" code snippets and "markdown-notes" code snippets (currently shown in the demo app with the `freestyle-palette-item` example, which uses the `fpi` slug).
### Proposal

Instead we should support different delimiters for different types of snippet content. For example: `// BEGIN-FREESTYLE-USAGE` vs `/* BEGIN-FREESTYLE-MARKDOWN`.
### Relevant Code
- https://github.com/chrislopresto/ember-freestyle/blob/a307ce0ec688d24d872e952bd191462471bb46ab/freestyle-usage-snippet-finder.js#L55-L58
- https://github.com/chrislopresto/ember-freestyle/blob/a307ce0ec688d24d872e952bd191462471bb46ab/addon/components/freestyle-usage.js#L22-L39
- https://github.com/chrislopresto/ember-freestyle/blob/a307ce0ec688d24d872e952bd191462471bb46ab/addon/templates/components/freestyle-usage.hbs#L14-L31

**Comment by lukemelia** [comment]
No longer relevant after snippets have been removed in #357
