### ISSUE TITLE
Remove "freestyle" controller app re-export?

### ISSUE THREAD

**Issue by bertdeblock** [chrislopresto/ember-freestyle#512]
Running `ember install ember-freestyle` already adds a `freestyle` controller to the user's project making the app re-export unnecessary. Personally, I always use `style-guide` as the name for my style-guide route, which means I will have both a `freestyle` and a `style-guide` controller in my app. I also think it's clearer to always have the user define the controller.
I wanted to PR this, but I can imagine people relying on this? So making a ticket instead first to see what other people think of this.

**Comment by lukemelia** [comment]
Perhaps we should make it a generator with a `--name` option and make `ember install ember-freestyle` emit console output making the user aware of the option to run the generator?

**Comment by bertdeblock** [comment]
So the default blueprint would not add the files anymore and instead the user should explicitly run a separate command which allows you to specify the route name? Sounds like a good idea.

https://github.com/chrislopresto/ember-freestyle/issues/33 Seems related btw.

**Comment by lukemelia** [comment]
> So the default blueprint would not add the files anymore and instead the user should explicitly run a separate command which allows you to specify the route name? Sounds like a good idea.

Correct.

> #33 Seems related btw.

Getting to close a 2016 issue would be a nice bonus!
