### ISSUE TITLE
Subsection navigation not present

### ISSUE THREAD

**Issue by boydkr** [chrislopresto/ember-freestyle#52]
I see there's a note in the readme about section yielding themselves to get subsection navigation, but it's not clear what that means.

**Comment by chrislopresto** [comment]
@boydkr Can you post some code snippets so we can see what's going on? The examples in the README should work as written.

**Comment by boydkr** [comment]
I've only gotten as far as installing the add-on and replacing the default fonts in the example template with my own.

I don't get the 'Typography' or 'Colors' subsections.

![screen shot 2016-05-10 at 1 32 53 pm](https://cloud.githubusercontent.com/assets/5815066/15158063/cda91a4e-16b3-11e6-8712-5e231134ac05.png)

**Comment by chrislopresto** [comment]
Strange. Are you getting any errors in the console? Can you inspect the DOM to see what's actually being rendered in the menu area?

**Comment by boydkr** [comment]
The submenu elements exist in the DOM, but aren't displayed.

It turns out that we had some wonderful legacy bootstrap css hanging around that was messing with some base elements in the nav 😢 .

Removing the offending css resolves the issue.

**Comment by chrislopresto** [comment]
Style guide for the win.. albeit in an indirect fashion here! Glad you tracked it down.
