### ISSUE TITLE
Style loading issues with freestyle page snapshot using @percy/ember 

### ISSUE THREAD

**Issue by sepuckett86** [chrislopresto/ember-freestyle#531]
I'm seeing this frequently (every other PR or so) as a Percy test failure (see image below). 

There appears to be an issue with loading the font style completely before the snapshot is taken, causing the diffs. 

Also, the backgrounds for the code snippets should be a dark color. This loads loads fine in our app, just not in the Percy snapshot.

So far I've tried adding test helpers like 'settled' and 'waitUntil' to the freestyle test but have so far been unsuccessful in solving this.

Thanks for any help on this - otherwise freestyle has been a great addition to our app!
Not sure if this is an issue for this repo, for Percy, or if it's specific to the repo I work in.

![Screen Shot 2021-03-31 at 2 20 49 PM](https://user-images.githubusercontent.com/29714675/113213550-2fea4d00-922d-11eb-9612-7e7557b6fae1.png)

**Comment by lukemelia** [comment]
@scanieso I don't have any experience troubleshooting this particular issue, but looking at your image, it makes me wonder if the text is being styled using a webfont, and that the timing of the font loading might be a culprit?

**Comment by scanieso** [comment]
Hey @lukemelia ! I think you meant to tag @sepuckett86 :)

**Comment by lukemelia** [comment]
Whoops, thanks @scanieso -- sorry for the errant notification! :-)

**Comment by sepuckett86** [comment]
@lukemelia Thanks for the response! I'll look into the font loading.

**Comment by bertdeblock** [comment]
Going to close this one for now due to no response, feel free to reopen if this is still an issue though!
