### ISSUE TITLE
Remove `pick` helper?

### ISSUE THREAD

**Issue by bertdeblock** [chrislopresto/ember-freestyle#591]
[ember-composable-helpers](https://github.com/DockYard/ember-composable-helpers) also provides a [pick](https://github.com/DockYard/ember-composable-helpers#pick) helper. In fact, the implementation is copy pasted from that one. Since `ember-composable-helpers` is quite a popular addon, it's not unrealistic that `ember-freestyle` users also make use of `ember-composable-helpers`. This makes it unclear which `pick` helper wins / is eventually used. I assume the one from `ember-freestyle` wins because it comes after `ember-composable-helpers` in the package file. In practice this is still okay as both implementations are the same, but it still seems better to avoid it. We can easily pick the wanted property from the native event inside the backing class.

**Comment by bertdeblock** [comment]
I have similar thoughts about the `is-present` helper in `ember-freestyle`. The name is very generic, so it's possible for a consuming app to have a helper with the same name, meaning `ember-freestyle` might end up using an `is-present` helper with a different implementation (as the helper in the consuming app wins). The components where this helper is used both have a backing class, so we can easily swap the usage of this helper with native getters.

**Comment by bertdeblock** [comment]
@lukemelia Any thoughts?

**Comment by lukemelia** [comment]
I'm with you. Approved the PR.
