### ISSUE TITLE
Allow notes to be placed before component and code example

### ISSUE THREAD

**Issue by vine77** [chrislopresto/ember-freestyle#69]
The problem is that the rendered component and the code for that component are not adjacent when there are notes due to [the ordering in freestyle-usage.hbs](https://github.com/chrislopresto/ember-freestyle/blob/150d96874112cd5e049f26e3bfa4ba359e25da63/addon/templates/components/freestyle-usage.hbs#L13-L25):

1. Rendered component
2. Notes
3. Code for rendered component

It should be possible to achieve an ordering like that of the [Bootstrap documentation](http://getbootstrap.com/components/#breadcrumbs), where a rendered example is always followed by its code:

1. Notes
2. Rendered component
3. Code for rendered component

**Comment by vine77** [comment]
@chrislopresto, thanks for all the work on this addon! I'm excited that we started using it in our enterprise app.

I'd be happy to submit a PR to add an option for note positioning if that sounds good. I'm assuming you'd like to maintain a default note position of "middle", between rendered component and code?

**Comment by chrislopresto** [comment]
Interesting. I wonder if your approach makes more sense overall. I just re-checked the style guide library that influenced the minimal Freestyle UI, and they also do it that way.

I'd rather just change the template than add a component option (unless there is an upswell of roaring objection of course).

Want to just PR the template change and include a screenshot?

Thanks!

**Comment by vine77** [comment]
Sounds good to me, @chrislopresto! PR submitted.
