### ISSUE TITLE
freestyle.css not loading in fresh ember-cli project

### ISSUE THREAD

**Issue by christophermlne** [chrislopresto/ember-freestyle#71]
I was hoping to get a compiled version of the css needed for freestyle, since our project uses less and we cannot switch to sass.

So I generated a new Ember project and installed the freestyle addon.

The addon install generator adds a link in the index.html head to 'freestyle.css'. This file is present, but blank.

Similarly the @import rule in styles/app.scss fails to import anything.

Please let me know if you need more information

**Comment by christophermlne** [comment]
if i try to compile directly with sass i get `error styles/components/freestyle-notes.scss (Line 12: File to import not found or unreadable: ../ember-freestyle/highlight.js/tomorrow-night.)`

**Comment by christophermlne** [comment]
i've had a chance to try out this project with various versions of ember in both existing and new projects, with different versions of ember-freestyle and haven't found a combination that will compile the stylesheets. i think there may be missing dependencies (missing bower.json).

the last thing i'll try before moving on is a git clone of the repo, and try to precompile the stylesheet there and copy to my project.

**Comment by chrislopresto** [comment]
@christophermlne It sounds like you need to add an explicit dependency on `ember-cli-sass` in your new Ember project. That will involve creating an `app/styles/app.scss` file. I would try getting the new app building and serving simple SCSS styles to make sure everything is set up properly.

Once you have that in place, the `ember-freestyle` generator should be able to take care of the rest. Just run `ember install ember-freestyle`. Among other things, it will attempt to add `@import 'ember-freestyle';` to `app/styles/app.scss`.

Let me know if this helps.

**Comment by christophermlne** [comment]
@chrislopresto ah that makes sense. i'll give it a shot and report back

**Comment by christophermlne** [comment]
This worked. Closing.
