### ISSUE TITLE
does not work on windows due to use of colon in filenames

### ISSUE THREAD

**Issue by zidjian257** [chrislopresto/ember-freestyle#72]
Just had a hard time to get this addon running on windows.
I know not many use windows as their operating system in the ember community, but unfortunatelly I have to, due to my employer  :-(

Running on windows the addon does not render **handlebars snippets** for `freestyle-usage` as well as **notes** do not work.

As I found out this is because the `freestyle-usage-snippet-finder` and the `freestyle-usage` component use  colons `:` to seperate the slug from notes and usage.
This is then used as temporary filenames on build time, which windows does not support.

To get it running I would suggest to use an underscore instead of the colon. What do you think?

**Comment by zidjian257** [comment]
Argh, all Tests Failed. As this broke backwords compability. I will take a Look to find a better aproach tomorrow

**Comment by zidjian257** [comment]
OK, looks good to me like this.
It now uses underscores for filenaming but, still allows using colons in the comments.

**Comment by misteroh** [comment]
It looks like using `notes` still doesn't work in Windows?
