### ISSUE TITLE
Get third-party dependencies from npm instead of Bower

### ISSUE THREAD

**Issue by josemarluedke** [chrislopresto/ember-freestyle#84]
Would be awesome to remove the bower deps of `remarkable` and `highlightjs` from this addon and use it from NPM instead.

**Comment by Sinled** [comment]
I second to this.

I removed bower from my application several weeks ago, and bower dependency stops me from using this addon directly inside my application.

**Comment by oligriffiths** [comment]
+1 Yes please since 2.11 has been releases and bower_components deprecated

**Comment by oligriffiths** [comment]
Found a quick solution to this for now:

```
npm install --save-dev highlightjs@9 remarkable@1.6.2
```
In `package.json` add 
```
"prepublish": "ln -sf ../node_modules/highlightjs bower_components/highlightjs && ln -sf ../node_modules/remarkable bower_components/remarkable",
```
under a `scripts` root node.

This should run the prepublish hook after installing and symlink the relevant bower components into node modules
