### ISSUE TITLE
UI / UX Improvements

### ISSUE THREAD

**Issue by bertdeblock** [chrislopresto/ember-freestyle#848]
I think we can make some minor adjustments to improve the look and feel of the default style guide:

- [x] Remove the uppercase transform for navigation menu items, I feel that uppercase words are harder to read and normal case just looks calmer overall https://github.com/chrislopresto/ember-freestyle/pull/973
- [ ] Introduce a visual difference between navigation menu headers and items, other than the current indentation
- [x] Make the navigation menu sticky, now you have to scroll back up to reach the navigation menu items - https://github.com/chrislopresto/ember-freestyle/pull/856

Feel free to add more suggestions.

I think we should also include something like `normalize.css` or `modern-normalize` _for the dummy app_ and adjust our styles accordingly as this is something that a lot of applications include themselves. This would make our styles more robust.

**Comment by lukemelia** [comment]
I like these suggestions 👍
