### ISSUE TITLE
Support usage indirection

### ISSUE THREAD

**Issue by jamesarosen** [chrislopresto/ember-freestyle#90]
I have 30 different icons whose docs each look like
```hbs
{{#freestyle-usage 'icon-pencil' title='Pencil'}}
  <svg class='icon pencil'>
    <use xlink:href="assets/my-app/icons.svg#pencil"></use>
  </svg>
{{/freestyle-usage}}
```
I wanted to DRY that up with something like
```hbs
{{#each icons as |icon|}}
  {{#freestyle-usage (concat 'icon-' icon.name) title=icon.title}}
    <svg class='icon {{icon.name}}'>
      <use xlink:href="assets/my-app/icons.svg#{{icon.name}}"></use>
    </svg>
  {{/freestyle-usage}}
{{/each}}
```
While the `rendered` block shows up fine, the code snippet is blank.

I also tried
```hbs
{{icon-usage usage name='pencil' title='Pencil'}}
{{icon-usage usage name='trash' title='Trashcan'}}
```
with
```hbs
{{!-- app/templates/components/icon-usage.hbs --}}
{{#freestyle-usage (concat 'icon-' name) title=title}}
  <svg class='icon {{name}}'>
    <use xlink:href="assets/my-app/icons.svg#{{name}}"></use>
  </svg>
{{/freestyle-usage}}
```
with the same effect.

Is there something I can do to make ember-freestyle pick up the fact that I want each of those to get a usage snippet?

**Comment by chrislopresto** [comment]
@jamesarosen Interesting use case. We should try to come up with a nice pattern for this.

Right now, the addon's snippet finder uses naive text matching during the build step to look for the opening and closing `freestyle-usage` curlies. It has no concept of usage within an iterator.

What you'd need to do right now is create separate snippet files and reference them by name in your `each` block. This would probably be annoying to maintain, but it would work.

I have been mulling over something that could be semi-related, so let me know if you want to chat / pair.

**Comment by jamesarosen** [comment]
Now that I think about it, perhaps I don't really want snippets for each of these. If they're really all variants on the same code, then I can do the code once at the top and then write all the instances as a table or a list or something.

**Comment by chrislopresto** [comment]
Ok. I'll close this in the meantime but continue to think this through.

Cheers.
