### ISSUE TITLE
freestyle-notes don't show up when using new _ syntax

### ISSUE THREAD

**Issue by danwenzel** [chrislopresto/ember-freestyle#99]
According to the [release notes for 0.2.14](https://github.com/chrislopresto/ember-freestyle/releases/tag/v0.2.14), we are now supposed to be using the new `_notes` syntax for `freestyle-note` instead of `:notes`.  

However, when using the new syntax, the notes are not showing up at all.  They _are_ still showing up using the old syntax.

**Comment by chrislopresto** [comment]
Thanks for reporting this. I'm on (computerless) vacation for the next week, but I'll take a look when I'm back.

**Comment by danwenzel** [comment]
@chrislopresto - Any updates on this?

**Comment by chrislopresto** [comment]
@danwenzel Somehow I must have fouled this up in 0.2.14. I went ahead and reintroduced the change here: https://github.com/chrislopresto/ember-freestyle/pull/117

I'll cut a v0.5.0 release, whose release notes will provide some deja vu.

Thanks for reporting and reminding me about this.
